### ISSUE TITLE
Как использовать хак

### ISSUE THREAD

**Issue by iZotex** [or75/Dota2Hack#1]
Привет, что нужно добавить или написать что бы работало? Скомпилировал заинжектил в доту нечего не показывает, и логов нету.

**Comment by or75** [comment]
Через Process Hacker инжекти, и видимо у тебя инжектор не x64 )

**Comment by iZotex** [comment]
Спасибо все заработало, ещё вопрос, как я понял интерфейса там нет через что я могу дописать его раз там есть sdk?
